#!/usr/bin/env python3
"""Generate main/paa_cert_data.cpp from all .der files in paa_cert/.

Run this after updating paa_cert/ with fetch_paa_certs.sh:
    python3 scripts/generate_paa_array.py

The generated file is compiled into the firmware so no separate SPIFFS
partition is needed.
"""

import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
CERT_DIR = PROJECT_ROOT / "paa_cert"
OUT_FILE = PROJECT_ROOT / "main" / "paa_cert_data.cpp"

HEADER = """\
// AUTO-GENERATED by scripts/generate_paa_array.py — do not edit by hand.
// Regenerate after updating paa_cert/ with scripts/fetch_paa_certs.sh.

#include "paa_certs_embedded.h"

"""


def cert_array_name(index: int) -> str:
    return f"kPAACertData_{index:04d}"


def format_bytes(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(indent + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    der_files = sorted(CERT_DIR.glob("*.der"))
    if not der_files:
        print(f"ERROR: no .der files found in {CERT_DIR}", file=sys.stderr)
        sys.exit(1)

    parts = [HEADER]

    # Emit one array per cert.
    for idx, path in enumerate(der_files):
        data = path.read_bytes()
        parts.append(
            f"// {path.name} ({len(data)} bytes)\n"
            f"static const uint8_t {cert_array_name(idx)}[] = {{\n"
            f"{format_bytes(data)}\n"
            f"}};\n\n"
        )

    # Emit the table.
    parts.append(
        "static const EmbeddedPAACert kPAACerts[] = {\n"
    )
    for idx, path in enumerate(der_files):
        data = path.read_bytes()
        parts.append(
            f"    {{ {cert_array_name(idx)}, {len(data)} }},  // {path.name}\n"
        )
    parts.append("};\n\n")
    parts.append(
        "const EmbeddedPAACert *embedded_paa_certs() { return kPAACerts; }\n"
        "size_t embedded_paa_certs_count() { return sizeof(kPAACerts) / sizeof(kPAACerts[0]); }\n"
    )

    OUT_FILE.write_text("".join(parts), encoding="utf-8")
    print(f"Generated {OUT_FILE} with {len(der_files)} certs.")


if __name__ == "__main__":
    main()
